security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db, championnat_db]

        in_memory:
            memory:
                users:
                    '%env(ADMIN_USER)%':
                        password: '%env(ADMIN_PASSWORD)%'
                        roles: 'ROLE_ADMIN'
        user_db:
            entity:
                class: App\Entity\Equipe
                property: login
        championnat_db:
            entity:
                class: App\Entity\Championnat
                property: id

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        App\Entity\Equipe:
            algorithm: bcrypt
            cost: 12
        App\Entity\Championnat:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_CHAMP
        ROLE_CHAMP: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: chain_provider

            guard:
                authenticators:
                    - App\Outils\CMAuthenticator

            remember_me:
               secret: '%kernel.secret%'

            logout:
                path: /api/logout
                success_handler: App\Outils\CMLogoutSuccessHandler

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
